wrap_comments = true
condense_wildcard_suffixes = true
empty_item_single_line = false
enum_discrim_align_threshold = 20
struct_field_align_threshold = 20
hex_literal_case = "Upper"
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
merge_derives = false
imports_granularity = "Module"
merge_imports = true
overflow_delimited_expr = true
group_imports = "StdExternalCrate"
struct_lit_single_line = true
use_field_init_shorthand = true
use_try_shorthand = true