[package]
name = "lexer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.3.1"
thiserror = "1.0.39"
# phf = "0.11.1"

[dependencies.phf]
version = "0.11.1"
features = ["macros"]
