[package]
name = "rush-base"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rush-parser = { path = "../rush-parser", version = "0.1.0" }
rush-core = { path = "../rush-core", version = "0.1.0" }
